### ISSUE TITLE
Find a solution to problems with git log

### ISSUE THREAD

**Issue by rm-code** [rm-code/logivi#12]
This error first occurred when I tested the [CDDA repository](https://github.com/CleverRaven/Cataclysm-DDA). It would always crash at a certain point and after doing some testing (see #8) I found out, that sometimes a file was marked as deleted in the git log:

```
D    example/path/foo.file
```

When LoGiVi sees a line like this in the log, it tracks it down in the graph and removes it. The issue is, that sometimes the same file shows up as being modified or deleted at a later point in the log:

```
M    example/path/foo.file
```

The crash in #8 simply happened because LoGiVi now tried to modify a file, which was no longer existing in the graph. The fix was to check if a file existed before trying to add a modifier on it. While the crash no longer happens, I'm a bit unhappy that some information from the git log has to be discarded.

I suspect it happens when a file is moved from one folder to the other on the main branch, while other people still modify it on a separate branch. When they merge it back into the main branch, the conflicts are resolved and the file is merged into the new location. This doesn't show in the log though.

So I'm wondering if there is a way to change the git log command used for LoGiVi, or any other way to solve this properly.

**Comment by josefnpat** [comment]
Perhaps you could soft-delete anything marked as `D`, and if another `M` comes up for that file, "un-delete" it so to speak.

**Comment by rm-code** [comment]
> Perhaps you could soft-delete anything marked as D, and if another M comes up for that file, "un-delete" it so to speak.

That's how I did it right at the start, but I think the number of "false-positives" is much higher this way. As far as I can tell a file which shows up as `M`odified, but is actually `D` already means that the modification happened to a different file. 

So "un-deleting" those files might lead to a wrong visualization of the repository.

**Comment by rm-code** [comment]
This is the ZeroBraneStudio repository viewed with [LoFiVi](https://github.com/rm-code/lofivi):
![lofivi](https://cloud.githubusercontent.com/assets/11627131/7221623/d20bfd9c-e6f1-11e4-9f6c-cc54ab0c76f1.png)
This is the ZeroBraneStudio repository viewed with [LoGiVi](https://github.com/rm-code/logivi):
![logivi](https://cloud.githubusercontent.com/assets/11627131/7221624/d3c5e3be-e6f1-11e4-81b2-7aabc29b35f0.png)
With the current approach (ignoring conflicting changes to files) the differences are minor, but noticeable.
