### ISSUE TITLE
NeoVim port?

### ISSUE THREAD

**Issue by timofonic** [rm-code/logivi#62]
Hello.

Any hopes to see this great tool ported to NeoVim?

What about a 2D GitHub-like form but more sophisticated? More advanced diff detection, etc.

Kind regards.

**Comment by rm-code** [comment]
Hi @timofonic,

thanks for your question, I currently don't have any plans to port this project.

> What about a 2D GitHub-like form but more sophisticated? More advanced diff detection, etc.

I am not sure what you mean by that. Could you please elaborate?

Best wishes
Robert

**Comment by rm-code** [comment]
Closing this due to lack of information. Feel free to open new issues for particular enhancements / features you want to see.
