### ISSUE TITLE
Crash with umlauts

### ISSUE THREAD

**Issue by rm-code** [rm-code/logivi#63]
When the user enters a repository name containing an umlaut (e.g. ö) it causes LoGiVi to crash.

```
Error: src/conf/RepositoryHandler.lua:38: table index is nil
stack traceback:
    src/conf/RepositoryHandler.lua:38: in function 'load'
    src/conf/RepositoryHandler.lua:71: in function 'init'
    src/screens/LoadingScreen.lua:141: in function 'init'
    lib/screenmanager/ScreenManager.lua:110: in function 'push'
    lib/screenmanager/ScreenManager.lua:80: in function 'switch'
    src/screens/InputPanel.lua:70: in function 'keypressed'
    lib/screenmanager/ScreenManager.lua:197: in function 'keypressed'
    main.lua:80: in function <main.lua:74>
    [string "boot.lua"]:454: in function <[string "boot.lua"]:435>
    [C]: in function 'xpcall'
```

![foo](https://cloud.githubusercontent.com/assets/11627131/15535571/3fddd24c-226e-11e6-879b-3301a7ec5aa9.gif)

**Comment by rm-code** [comment]
Might be able to handle this nicely with Lua's UTF-8 library.

**Comment by rm-code** [comment]
Problem is caused by the regex pattern in the RepositoryHandler 

``` lua
local key, value = line:match( '^%s*([%g%s]*%g)%s*=%s*(.+)$' );
```

This returns nil if the line contains umlauts.

**Comment by rm-code** [comment]
Might be able to solve this via:

``` lua
function Utility.splitLine( line, delimiter )
    local tmp = {};
    for part in line:gmatch( '[^' .. delimiter .. ']+' ) do
        tmp[#tmp + 1] = part;
    end
    return tmp;
end
```

This seems to split the lines just fine, but causes problem when comparing the strings to the ones loaded via:

``` lua
for _, name in ipairs( love.filesystem.getDirectoryItems( dir )) do
```

**Comment by rm-code** [comment]
Looks like the "string" returned by the love.filesystem function has a different encoding than UTF-8 ... 😦 

``` lua
local function searchLog( name )
    print("== Search " .. name)
    for p, c in utf8.codes(name) do
        print(p, c)
    end

    for i, log in ipairs( list ) do
        print("== Loaded " .. log.name)
        for p, c in utf8.codes(log.name) do
            print(p, c)
        end

        if log.name == name then
            return i;
        end
    end
end
```

```
== Search LÖVE-API
1   76
2   214
4   86
5   69
6   45
7   65
8   80
9   73
== Loaded LÖVE-API
1   76
2   79
3   776
5   86
6   69
7   45
8   65
9   80
10  73
```

**Comment by danielniccoli** [comment]
> Looks like the "string" returned by the love.filesystem function has a different encoding than UTF-8 ... 😦

It's both UTF-8 encoded Unicode. 

The lower example shows the same text using [grapheme clusters](http://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries) (“user-perceived characters”), which consists of a *letter* and a *combining mark*.

```
1    L
2    O    (Latin Capital Letter O)
3    ̈    (Combining Diaeresis)
4    V
```


The `love.filesystem` function returns the string in normalized form D (NFD). Why it does so, I don't know. One possibility would be that Apple does normalize Unicode strings before storing them and love.filesystem calls the macOS API that then returns the normalized string.

You could either modify your regular expression (http://www.regular-expressions.info/unicode.html).

Or simply try to normalize the Unicode string to NFC.

In Python that would look like this:

```python
"Ö".encode("utf8)  # Show Hex Value of Code Point 214
# b'\xc3\x96'

unicodedata.normalize("NFD", b'\xc3\x96'.decode()).encode("utf8")  # Normalize 'O' to NFD ('O' + ' ̈ ')
# b'\x4f\xcc\x88'

unicodedata.normalize('NFC', b'\x4f\xcc\x88'.decode())  # Normalize 'O +  ̈ ' to NFC ('Ö')
# 'Ö'
```



Some sources:
http://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries
http://unicode.org/faq/normalization.html
https://unicode-table.com/en/
https://docs.python.org/3.6/library/unicodedata.html#unicodedata.normalize
